name: build-and-push
on:
  push:
    branches:
      - "*"
  schedule:
    # rebuild every day for security
    - cron:  '0 20 * * *'

jobs:
  build-and-push:
    strategy:
      fail-fast: true
      matrix:
        year: ["2022"]
        nodejs: ["16"]
        python: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}

      - name: Timestamp
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDD'

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms
          # - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
          # - https://hub.docker.com/layers/amazonlinux/library/amazonlinux/2022/images/sha256-c74e77c670519cd69e3f5ce3fa714c02c582a40d786dd7e97113e717e7655e4d?context=explore
          platforms: linux/amd64,linux/arm64/v8
          push: true
          # multiple tags https://github.com/docker/build-push-action#customizing
          # ternary https://github.com/actions/runner/issues/409#issuecomment-752775072
          # latest automatically applied https://stackoverflow.com/questions/22080706/how-to-create-named-and-latest-tag-in-docker#comment85790276_36398336
          tags: |
            fromtheexchange/aws-lambda-ric:amazonlinux${{ matrix.year }}-nodejs${{ matrix.nodejs }}-python${{ matrix.python }}
            fromtheexchange/aws-lambda-ric:amazonlinux${{ matrix.year }}-nodejs${{ matrix.nodejs }}-python${{ matrix.python }}-${{ steps.time.outputs.time }}

            ${{ matrix.python == '3.9' && format('fromtheexchange/aws-lambda-ric:amazonlinux{0}-nodejs{1}', matrix.year, matrix.nodejs) || ''}}
            ${{ matrix.nodejs == '16' && format('fromtheexchange/aws-lambda-ric:amazonlinux{0}-python{1}', matrix.year, matrix.python) || ''}}
            ${{ matrix.nodejs == '16' && matrix.python == '3.9' && format('fromtheexchange/aws-lambda-ric:amazonlinux{0}', matrix.year) || ''}}
            ${{ matrix.year == '2022' && matrix.python == '3.9' && format('fromtheexchange/aws-lambda-ric:nodejs{0}', matrix.nodejs) || ''}}
            ${{ matrix.year == '2022' && matrix.nodejs == '16' && format('fromtheexchange/aws-lambda-ric:python{0}', matrix.python) || ''}}

            ${{ matrix.year == '2022' && matrix.nodejs == '16' && matrix.python == '3.9' && 'fromtheexchange/aws-lambda-ric:latest' || ''}}

          # FUTURE: temporarily disable, as amazonlinux:2022 only supports nodejs, without versions
          # NODEJS=${{ matrix.nodejs }}
          build-args: |
            YEAR=${{ matrix.year }}
            PYTHON=${{ matrix.python }}

  sync-readme:
    needs: "build-and-push"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }}
        repository: fromtheexchange/aws-lambda-ric
        readme: "./README.md"
